title: VibeIn
author: Jake DeLeeuw
email: jakedeleeuw032@gmail.com
description: >
  Hi, Iâ€™m Jake. I talk about vibe coding, project management, and products I build. I share insights from the business world and my experiences
  creating products from idea to launch.

baseurl: "/VibeIn"  # <-- The added line

google_analytics: G-EC698MZSG0

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- resume.md
  # 'github.md' previously pointed to your LinkedIn page; removed from header_pages to hide from nav

footer_icons:
- username: jakedeleeuw032
  url: https://github.com/jakedeleeuw032
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

